# Generated by Django 3.1.4 on 2023-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20230510_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonupload',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
