# Generated by Django 3.1.4 on 2023-05-10 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_auto_20230510_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georecord',
            name='geometry_zoom_10',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='georecord',
            name='geometry_zoom_12',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='georecord',
            name='geometry_zoom_8',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
