# Generated by Django 3.1.4 on 2020-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadnum', models.TextField()),
                ('koatuu', models.TextField()),
                ('purpose', models.TextField()),
                ('purpose_code', models.TextField()),
            ],
            options={
                'db_table': 'landuse',
                'managed': False,
            },
        ),
    ]
