# Generated by Django 3.1.4 on 2021-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadinfo', '0002_koatuu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koatuu',
            options={'managed': False},
        ),
    ]
