# Generated by Django 3.1.4 on 2022-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadinfo', '0003_auto_20211127_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[['in_progress', 'in_progress'], ['success', 'success'], ['error', 'error']], max_length=30)),
            ],
        ),
        migrations.AlterModelTable(
            name='koatuu',
            table='koatuu',
        ),
    ]
