# Generated by Django 3.1.4 on 2022-01-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadinfo', '0005_update_latest_koatuu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='latest_koatuu',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
