# Generated by Django 3.1.4 on 2022-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadinfo', '0006_auto_20220117_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='latest_level',
            field=models.IntegerField(default=1),
        ),
    ]
