# Generated by Django 3.1.4 on 2022-02-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadinfo', '0010_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanduseChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadnum', models.CharField(max_length=25)),
                ('action', models.CharField(choices=[['create', 'create'], ['delete', 'delete'], ['update', 'update']], max_length=10)),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diff_next', to='cadinfo.update')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diff_previous', to='cadinfo.update')),
            ],
        ),
    ]
