# Generated by Django 3.1.4 on 2022-02-04 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadinfo', '0011_landusechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='landusechange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
